[2023-06-28T13:50:38.944+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: load_pageviews.extract_data __airflow_temporary_run_2023-06-28T13:50:30.775074+00:00__ [queued]>
[2023-06-28T13:50:38.952+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: load_pageviews.extract_data __airflow_temporary_run_2023-06-28T13:50:30.775074+00:00__ [queued]>
[2023-06-28T13:50:38.952+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-28T13:50:38.952+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-06-28T13:50:38.952+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-28T13:50:38.964+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): extract_data> on 2023-06-28 00:00:00+00:00
[2023-06-28T13:50:38.970+0000] {standard_task_runner.py:55} INFO - Started process 5282 to run task
[2023-06-28T13:50:38.973+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'load_pageviews', 'extract_data', '__***_temporary_run_2023-06-28T13:50:30.775074+00:00__', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/load_pageviews.py', '--cfg-path', '/tmp/tmp4ud55ii_']
[2023-06-28T13:50:38.974+0000] {standard_task_runner.py:83} INFO - Job 113: Subtask extract_data
[2023-06-28T13:50:39.022+0000] {task_command.py:389} INFO - Running <TaskInstance: load_pageviews.extract_data __airflow_temporary_run_2023-06-28T13:50:30.775074+00:00__ [running]> on host 3e2e38946fac
[2023-06-28T13:50:39.077+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_pageviews
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-06-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=__***_temporary_run_2023-06-28T13:50:30.775074+00:00__
[2023-06-28T13:50:39.078+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-28T13:50:39.079+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -o /tmp/wikipageviews.gz https://dumps.wikimedia.org/other/pageviews/2023/2023-06/pageviews-20230628-110000.gz']
[2023-06-28T13:50:39.091+0000] {subprocess.py:86} INFO - Output:
[2023-06-28T13:50:39.102+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-06-28T13:50:39.102+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-06-28T13:50:54.109+0000] {local_task_job.py:224} WARNING - State of this instance has been externally set to None. Terminating instance.
[2023-06-28T13:50:54.111+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 5282. PIDs of all processes in the group: [5283, 5282]
[2023-06-28T13:50:54.111+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 5282
[2023-06-28T13:50:54.112+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-06-28T13:50:54.112+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2023-06-28T13:50:54.121+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 191, in execute
    cwd=self.cwd,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-06-28T13:50:54.126+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=load_pageviews, task_id=extract_data, execution_date=20230628T000000, start_date=20230628T135038, end_date=20230628T135054
[2023-06-28T13:50:54.138+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 113 for task extract_data ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(load_pageviews, extract_data, __airflow_temporary_run_2023-06-28T13:50:30.775074+00:00__, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'extract_data', 'dag_id': 'load_pageviews', 'run_id': '__airflow_temporary_run_2023-06-28T13:50:30.775074+00:00__', 'map_index': -1, 'start_date': datetime.datetime(2023, 6, 28, 13, 50, 38, 945274, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2023, 6, 28, 13, 50, 54, 125925, tzinfo=Timezone('UTC')), 'duration': 15}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 5282)
[2023-06-28T13:50:54.163+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=5282, status='terminated', exitcode=1, started='13:50:38') (5282) terminated with exit code 1
[2023-06-28T13:50:54.164+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=5283, status='terminated', started='13:50:38') (5283) terminated with exit code None
